//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperSimpleStocks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperSimpleStocks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPERSIMPLESTOCKS_ERR_001 - Not permitted stock type value [{0}]. Permitted values are [{1}].
        /// </summary>
        internal static string SUPERSIMPLESTOCKS_ERR_001 {
            get {
                return ResourceManager.GetString("SUPERSIMPLESTOCKS_ERR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPERSIMPLESTOCKS_ERR_002 - Not permitted trade type value [{0}]. Permitted values are [{1}].
        /// </summary>
        internal static string SUPERSIMPLESTOCKS_ERR_002 {
            get {
                return ResourceManager.GetString("SUPERSIMPLESTOCKS_ERR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPERSIMPLESTOCKS_ERR_003 - Not found stock symbol [{0}] in trades in the last 15 minutes.
        /// </summary>
        internal static string SUPERSIMPLESTOCKS_ERR_003 {
            get {
                return ResourceManager.GetString("SUPERSIMPLESTOCKS_ERR_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPERSIMPLESTOCKS_ERR_004 - Error recording trade [{0}]. Inner exception --&gt; {1}.
        /// </summary>
        internal static string SUPERSIMPLESTOCKS_ERR_004 {
            get {
                return ResourceManager.GetString("SUPERSIMPLESTOCKS_ERR_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPERSIMPLESTOCKS_ERR_005 - The value [{0}] of the attribute [{1}] must be not negative.
        /// </summary>
        internal static string SUPERSIMPLESTOCKS_ERR_005 {
            get {
                return ResourceManager.GetString("SUPERSIMPLESTOCKS_ERR_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPERSIMPLESTOCKS_ERR_006 - The value [{0}] of the attribute [{1}] must be greater than 0.
        /// </summary>
        internal static string SUPERSIMPLESTOCKS_ERR_006 {
            get {
                return ResourceManager.GetString("SUPERSIMPLESTOCKS_ERR_006", resourceCulture);
            }
        }
    }
}
